services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: always
  
  redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - "5002:6379"
    restart: always
    
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"
      - "4317:18889"
    container_name: aspire-dashboard
    restart: unless-stopped

volumes:
  sqlserverdata:
    driver: local